# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

huber_weight <- function(x, cw) {
    .Call('_MyFPLM_huber_weight', PACKAGE = 'MyFPLM', x, cw)
}

huber_rho <- function(x, cw) {
    .Call('_MyFPLM_huber_rho', PACKAGE = 'MyFPLM', x, cw)
}

huber_estimates <- function(X, y, beta, cw, tol) {
    .Call('_MyFPLM_huber_estimates', PACKAGE = 'MyFPLM', X, y, beta, cw, tol)
}

